{{- if and .Values.litellm.enabled .Values.litellm.serviceAccount.create }}
{{- $annotations := mergeOverwrite (dict) .Values.serviceAccount.annotations .Values.litellm.serviceAccount.annotations }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tracecat.litellmServiceAccountName" . }}
  labels:
    {{- include "tracecat.labels" . | nindent 4 }}
    app.kubernetes.io/component: litellm
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
